# Generated by Django 2.1.2 on 2018-10-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritagesites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False, 'ordering': ['location_id'], 'verbose_name': 'UNESCO Heritage Location', 'verbose_name_plural': 'UNESCO Heritage Locations'},
        ),
    ]
